package com.myspace.demo_bancolombia;


import com.myspace.demo_bancolombia.Transaccion;


rule "All OK" 
ruleflow-group 'reglasBancolombia'
when     
    //$t: Transaccion( existsInAccount == true, existsInLog == true, matchesValue == true )
    $t: Transaccion( existeCuenta == true, existeLog == true, isEqualValues()) 
then     
    modify($t){
        setResultRules("ALL_OK");
    } 
end  

rule "Gabetas OK" 
ruleflow-group 'reglasBancolombia'
when     
    $t: Transaccion( existeCuenta == false, existeLog == true, isEqualValues()) 
then     
    modify($t){
        setResultRules("NO_EXISTE_CUENTA");
    } 
end  

rule "Gabetas modified " 
ruleflow-group 'reglasBancolombia'
when     
    $t: Transaccion( existeCuenta == true, existeLog == true, isEqualValues() == false ) 
then     
    modify($t){         
        setValor(Math.Abs(valorCuenta - valorLog));         
        setResultRules("VALOR_NO_COINCIDE");
    } 
end