package com.myspace.demo_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Cedula")
	private java.lang.String cedula;
	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;

	public Cliente() {
	}

	public java.lang.String getCedula() {
		return this.cedula;
	}

	public void setCedula(java.lang.String cedula) {
		this.cedula = cedula;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public Cliente(java.lang.String cedula, java.lang.String nombre) {
		this.cedula = cedula;
		this.nombre = nombre;
	}

}