package com.myspace.demo_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Cliente() {
    }




}