package com.myspace.demo_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class MovimientoReply implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Existe")
	private java.lang.Boolean existe;
	@org.kie.api.definition.type.Label(value = "Fecha")
	private java.lang.String fecha;
	@org.kie.api.definition.type.Label(value = "Numero de Cuenta")
	private java.lang.String numCuenta;
	@org.kie.api.definition.type.Label(value = "Valor")
	private java.lang.Double valor;

	public MovimientoReply() {
	}

	public java.lang.Boolean getExiste() {
		return this.existe;
	}

	public void setExiste(java.lang.Boolean existe) {
		this.existe = existe;
	}

	public java.lang.String getFecha() {
		return this.fecha;
	}

	public void setFecha(java.lang.String fecha) {
		this.fecha = fecha;
	}

	public java.lang.String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(java.lang.String numCuenta) {
		this.numCuenta = numCuenta;
	}

	public java.lang.Double getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Double valor) {
		this.valor = valor;
	}

	public MovimientoReply(java.lang.Boolean existe, java.lang.String fecha,
			java.lang.String numCuenta, java.lang.Double valor) {
		this.existe = existe;
		this.fecha = fecha;
		this.numCuenta = numCuenta;
		this.valor = valor;
	}

}