package com.myspace.demo_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class VerificarClienteReply implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Numero de Cuenta")
	private java.lang.String numCuenta;

	public VerificarClienteReply() {
	}

	public java.lang.String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(java.lang.String numCuenta) {
		this.numCuenta = numCuenta;
	}

	public VerificarClienteReply(java.lang.String numCuenta) {
		this.numCuenta = numCuenta;
	}

}